name: dotnet-10-setup
description: .NET 10 SDK をセットアップして環境を準備する GitHub Copilot Coding Agent
version: 1.0.0

tasks:
  - name: setup-dotnet-10
    description: .NET 10 SDK のインストールとワークロードのセットアップ
    steps:
      - name: Check .NET version
        description: 現在インストールされている .NET SDK のバージョンを確認
        command: dotnet --version
        
      - name: Install .NET 10 SDK
        description: .NET 10 SDK をインストール
        instructions: |
          # .NET 10 SDK のダウンロードとインストール
          # 環境に応じた適切なインストール方法を使用してください
          
          ## Windows
          - https://dotnet.microsoft.com/download/dotnet/10.0 から最新のインストーラーをダウンロード
          - インストーラーを実行して指示に従う
          
          ## macOS
          ```bash
          brew install dotnet@10
          ```
          
          ## Linux (Ubuntu/Debian)
          ```bash
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --channel 10.0
          ```
          
      - name: Verify .NET 10 installation
        description: .NET 10 SDK が正しくインストールされたことを確認
        command: dotnet --list-sdks
        expected_output_contains: "10.0"
        
      - name: Install Aspire workload
        description: .NET Aspire ワークロードをインストール
        command: dotnet workload install aspire
        
      - name: Update global.json
        description: プロジェクトが .NET 10 SDK を使用するように global.json を更新
        instructions: |
          プロジェクトルートに global.json を作成または更新:
          ```json
          {
            "sdk": {
              "version": "10.0.100",
              "rollForward": "latestMinor"
            }
          }
          ```
          
      - name: Restore dependencies
        description: NuGet パッケージの依存関係を復元
        command: dotnet restore
        working_directory: ./
        
      - name: Clean build
        description: クリーンビルドを実行して環境を確認
        command: dotnet clean && dotnet build
        working_directory: ./
        
      - name: Verify setup
        description: セットアップが完全に完了したことを確認
        command: dotnet run --project src/AppHost --no-build
        timeout: 30
        notes: |
          - Aspire AppHost が正常に起動することを確認
          - エラーが発生した場合は、ログを確認してトラブルシューティング

validation:
  - dotnet_version: ">=10.0.0"
  - aspire_workload_installed: true
  - build_successful: true

notes: |
  このエージェントは以下のタスクを実行します:
  1. 現在の .NET SDK バージョンを確認
  2. .NET 10 SDK をインストール
  3. Aspire ワークロードをインストール
  4. global.json を更新
  5. 依存関係を復元
  6. ビルドとテスト実行で環境を検証

troubleshooting:
  - issue: ".NET 10 SDK が見つからない"
    solution: "公式サイトから最新のプレビュー版をダウンロードしてください"
  - issue: "Aspire ワークロードのインストールに失敗"
    solution: "dotnet workload update を実行してから再試行してください"
  - issue: "ビルドエラーが発生"
    solution: "dotnet clean を実行してから dotnet restore を再実行してください"